### PR TITLE
➕ Add Endurance Main and Test Network Deployments

### PR DESCRIPTION
**Pull request by shelchin2023**
### 🕓 Changelog

Add Endurance test and main network deployments:
- [Endurance](https://explorer-endurance.fusionist.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [Endurance Testnet](https://myexplorertestnet.fusionist.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).

#### Verification

Compare the `keccak256` hash of the runtime bytecode with the canonical `keccak256` hash of the runtime bytecode [here](https://github.com/pcaversaccio/createx#security-considerations):

```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://myrpctestnet.fusionist.io)
0xbd8a7ea8cfca7b4e5f5041d7d4b17bc317c5ce42cfbc42066a00cf26b43eb53f

~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://rpc-endurance.fusionist.io)
0xbd8a7ea8cfca7b4e5f5041d7d4b17bc317c5ce42cfbc42066a00cf26b43eb53f
```
 
#### 🐶 Cute Animal Picture

image

### CODE REVIEW

**Comment by pcaversaccio** [comment]
Thanks, will amend the PR slightly later. I removed OP-Endurance test network yesterday since the block explorer is completely shut down (see https://github.com/pcaversaccio/createx/pull/96). Is this correct?

**Comment by pcaversaccio** [comment]
Ah no it's here now: https://myexplorertestnet.fusionist.io :). Will re-add the test network in that case.

**Review by pcaversaccio — APPROVED** [review]
Added the test network deployment as well & verified all contracts including on sourcify for the mainnet.

**Comment by shelchin2023** [comment]
Hello @pcaversaccio,

Thank you very much for your quick merge.
We noticed that the Endurance test network information you previously added is not intended for long-term public use. 
To ensure accuracy and protection of information, we kindly request that you delete this test network from your repos. 

`  {
    "name": "Endurance Testnet",
    "chainId": 6480,
    "urls": [
      "https://myexplorertestnet.fusionist.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
    ]
  `}

**Comment by pcaversaccio** [comment]
> Hello @pcaversaccio,
> 
> Thank you very much for your quick merge. We noticed that the Endurance test network information you previously added is not intended for long-term public use. To ensure accuracy and protection of information, we kindly request that you delete this test network from your repos.
> 
> ` { "name": "Endurance Testnet", "chainId": 6480, "urls": [ "https://myexplorertestnet.fusionist.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed" ]`}

Gotcha, addressed via https://github.com/pcaversaccio/createx/commit/f7030198e28a817878184f10a2ce17dec3d32c85.

**Pull request merged**
